// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Bu7ezeSFnTcZBe6LQo7kXbtW-e-D53E',
    appId: '1:536013684311:web:0f4dc913935b46b6032d12',
    messagingSenderId: '536013684311',
    projectId: 'raspberrypi-f5471',
    authDomain: 'raspberrypi-f5471.firebaseapp.com',
    databaseURL: 'https://raspberrypi-f5471-default-rtdb.firebaseio.com',
    storageBucket: 'raspberrypi-f5471.firebasestorage.app',
    measurementId: 'G-H65EYKJPFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPloOn8zquqoyZqaCNZuGlgvxPuzxwxQ',
    appId: '1:536013684311:android:421c979a17e21e1a032d12',
    messagingSenderId: '536013684311',
    projectId: 'raspberrypi-f5471',
    databaseURL: 'https://raspberrypi-f5471-default-rtdb.firebaseio.com',
    storageBucket: 'raspberrypi-f5471.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCedggzvpfnKu0Gp0YkDHK6Z7UoZbvStnw',
    appId: '1:536013684311:ios:cc8b6e0cfde5ac9a032d12',
    messagingSenderId: '536013684311',
    projectId: 'raspberrypi-f5471',
    databaseURL: 'https://raspberrypi-f5471-default-rtdb.firebaseio.com',
    storageBucket: 'raspberrypi-f5471.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCedggzvpfnKu0Gp0YkDHK6Z7UoZbvStnw',
    appId: '1:536013684311:ios:cc8b6e0cfde5ac9a032d12',
    messagingSenderId: '536013684311',
    projectId: 'raspberrypi-f5471',
    databaseURL: 'https://raspberrypi-f5471-default-rtdb.firebaseio.com',
    storageBucket: 'raspberrypi-f5471.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Bu7ezeSFnTcZBe6LQo7kXbtW-e-D53E',
    appId: '1:536013684311:web:5eaf804ee816e0d6032d12',
    messagingSenderId: '536013684311',
    projectId: 'raspberrypi-f5471',
    authDomain: 'raspberrypi-f5471.firebaseapp.com',
    databaseURL: 'https://raspberrypi-f5471-default-rtdb.firebaseio.com',
    storageBucket: 'raspberrypi-f5471.firebasestorage.app',
    measurementId: 'G-ZKX2PYY1YT',
  );
}
